/controller_node:
  ros__parameters:
    Ka0: 0.0
    Ka1: 0.0
    Ka2: 0.0
    Kp0: 4.1
    Kp1: 4.1
    Kp2: 4.1
    Kv0: 2.0
    Kv1: 2.0
    Kv2: 2.0
    Kvi0: 0.0
    Kvi1: 0.0
    Kvi2: 0.0
    cmd_topic: /fmu/vehicle_attitude_setpoint/in
    ctrl_rate: 125.0
    gra: 9.81
    hov_percent: 0.7
    i_limit_max: 0.5
    i_speed_max: 1.5
    mass: 1.535

