/controller_node:
  ros__parameters:
    Kp0: 12.0
    Kp1: 12.0
    Kp2: 12.0
    Kv0: 5.0
    Kv1: 5.0
    Kv2: 5.0
    Ki0: 0.0
    Ki1: 0.0
    Ki2: 0.0
    cmd_topic: /fmu/vehicle_attitude_setpoint/in
    ctrl_rate: 80.0
    gra: 9.81
    hov_percent: 0.7
    i_limit_max: 1.0
    i_c: 1.0
    mass: 1.535

